### ISSUE TITLE
Gauss2DSamples

### ISSUE THREAD

**Issue by creold** [mobeets/illustrator-scripts#1]
Hi, Jay. 
It was nice to see in your script that variables are taken from my scripts for Adobe Illustrator =)
But the error of the open document is wrong for you. The `LANG_ERR_DOC` variable is not declared. I had a text written in the variable for different localizations (English, Russian)
`if (documents.length == 0) {
  alert(LANG_ERR_DOC);
  return;
}`

**Comment by creold** [comment]
Sample
```
$.localize = true; // Enabling automatic localization
var LANG_ERR_DOC = { en: 'Open a document and try again', ru: 'Откройте документ и запустите скрипт'};
if (documents.length == 0) { alert(LANG_ERR_DOC); }
```

**Comment by mobeets** [comment]
Ah good point, thanks!
